# ============================================================
# 00b_figure_index.R  —  Trade Capstone
# Generates FIGURE_INDEX.md — authoritative mapping of
# slide number → figure filename → R script that creates it.
# Run any time after pipeline changes to keep docs in sync.
# ============================================================

library(dplyr)

figures <- tribble(
  ~slide,   ~role,         ~filename,                          ~r_script,               ~notes,
  # ── MAIN DECK ──────────────────────────────────────────────
  "2",      "stats grid",  "(built in JS — no PNG)",           "build_deck.js",          "5 stat cards built directly in pptxgenjs",
  "3",      "main figure", "fig1_resolution_contrast_v2.png",  "16_fig1_enhanced.R",     "two-panel: scatter + aggregation path",
  "4",      "main figure", "fig2_hs6_import_effect.png",       "09_final_figures.R",     "Trump 1 dose-response scatter",
  "5",      "main figure", "fig10_predictive_validation.png",  "17_predictive_validation.R", "T1 model OOS on T2 data",
  "6",      "main figure", "fig13_inrange_validation.png",     "24_inrange_validation.R","*rename from fig_inrange_validation.png",
  "7",      "main figure", "fig7_trump1_vs_trump2.png",        "13_trump_comparison.R",  "side-by-side slope comparison",
  "8",      "main figure", "figA5_bucket_comparison.png",      "22_bucket_comparison.R", "T1 staircase vs T2 flat",
  "9",      "main figure", "fig15_diversion_by_country.png",   "27_diversion_test.R",    "3-country panel (Mexico/Taiwan/Vietnam)",
  "10",     "main figure", "fig11b_disruption_prob.png",       "18_logistic_hs6.R",      "logistic S-curve",
  "11",     "main figure", "fig11c_logistic_coefficients.png", "18_logistic_hs6.R",      "coefficient forest plot",
  "12",     "main figure", "fig12_model_comparison.png",       "20_model_comparison.R",  "three-model ROC curves",
  "13",     "text only",   "(no figure)",                      "build_deck.js",          "what we know / don't know",
  "14",     "text only",   "(no figure)",                      "build_deck.js",          "four lessons + 14.5¢ callout",
  # ── APPENDIX ───────────────────────────────────────────────
  "A1",     "main figure", "figA1_hs_hierarchy.png",           "21_appendix_methods.R",  "HS2→HS4→HS6 classification tree",
  "A2",     "main figure", "figA2_tariff_distribution.png",    "21_appendix_methods.R",  "optional — placeholder if missing",
  "A3",     "main figure", "figA3_merge_flow.png",             "21_appendix_methods.R",  "data merge flow + match rates",
  "A4",     "main figure", "figA4_tariff_timeline.png",        "21_appendix_methods.R",  "tariff escalation timeline 2018–2026",
  "A5",     "main figure", "figA5_bucket_comparison.png",      "22_bucket_comparison.R", "same as slide 8",
  "A6",     "main figure", "figA6_elasticity_dose_response.png","23_elasticity_extension.R","T1 fan vs T2 flat by elasticity group",
  "A7",     "fig top",     "fig15_diversion_by_country.png",   "27_diversion_test.R",    "same as slide 9",
  "A7",     "fig bottom",  "fig14_diversion_scatter.png",      "27_diversion_test.R",    "combined scatter with regression line",
)

# ── Write FIGURE_INDEX.md ─────────────────────────────────────
lines <- c(
  "# Figure Index",
  "## When Tariffs Stop Moving Trade — complete figure inventory",
  "### Auto-generated by 00b_figure_index.R",
  paste0("### Last run: ", Sys.time()),
  "",
  "---",
  "",
  "## Main deck (slides 1–14)",
  "",
  "| Slide | Figure filename | R script | Notes |",
  "|-------|----------------|---------|-------|"
)

main <- figures %>% filter(!grepl("^A", slide))
for (i in seq_len(nrow(main))) {
  r <- main[i,]
  lines <- c(lines,
    paste0("| ", r$slide, " | `", r$filename, "` | `", r$r_script, "` | ", r$notes, " |"))
}

lines <- c(lines, "",
  "## Appendix (slides A1–A7)",
  "",
  "| Slide | Figure filename | R script | Notes |",
  "|-------|----------------|---------|-------|"
)

app <- figures %>% filter(grepl("^A", slide))
for (i in seq_len(nrow(app))) {
  r <- app[i,]
  lines <- c(lines,
    paste0("| ", r$slide, " | `", r$filename, "` | `", r$r_script, "` | ", r$notes, " |"))
}

lines <- c(lines, "",
  "---",
  "",
  "## Important notes",
  "",
  "**fig13 rename required:**",
  "Script 24 saves `figures/fig_inrange_validation.png`.",
  "Before running `node build_deck.js`, rename it:",
  "```bash",
  "cp figures/fig_inrange_validation.png figures/fig13_inrange_validation.png",
  "```",
  "",
  "**figA2 is optional:**",
  "If `figA2_tariff_distribution.png` is missing, slide A2 shows a placeholder.",
  "Run `scripts/21_appendix_methods.R` to regenerate.",
  "",
  "**figA5 appears twice:**",
  "Used as the main figure on slide 8 and again as appendix A5.",
  "",
  "**fig15 appears twice:**",
  "Used as the main figure on slide 9 and as the top figure on appendix A7.",
  "",
  "**Deck builder:**",
  "`node build_deck.js` reads all figures from `figures/` directory.",
  "Override with: `FIG_DIR=/path/to/figures node build_deck.js`",
  "",
  "**Total slides:** 21 (14 main + appendix divider + A1–A7 appendix)"
)

writeLines(lines, "outputs/FIGURE_INDEX.md")
cat("Saved outputs/FIGURE_INDEX.md\n")

# ── Also print a quick console summary ───────────────────────
cat("\n=== FIGURE INDEX SUMMARY ===\n")
cat(sprintf("%-6s  %-48s  %s\n", "SLIDE", "FILENAME", "SCRIPT"))
cat(strrep("-", 80), "\n")
for (i in seq_len(nrow(figures))) {
  r <- figures[i,]
  cat(sprintf("%-6s  %-48s  %s\n",
    r$slide,
    substr(r$filename, 1, 48),
    r$r_script))
}
